name: Nix

on: [push, pull_request, workflow_dispatch]

jobs:
  update-inputs:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    concurrency:
      group: nixupdateinputs
      cancel-in-progress: true
    uses: ./.github/workflows/nix-update-inputs.yml
    secrets: inherit

  build:
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    concurrency:
      group: nixbuild
      cancel-in-progress: true
    needs: update-inputs
    uses: ./.github/workflows/nix-build.yml
    secrets: inherit
